apiVersion: v1
kind: ServiceAccount
metadata:
  name: home-assistant
  namespace: home-assistant
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: node-red
  namespace: home-assistant
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: matter-server
  namespace: home-assistant
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mosquitto
  namespace: home-assistant
automountServiceAccountToken: false
