apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - external-secrets
  - cert-manager
  - cloudnative-pg
  - traefik
  - external-dns
  - authentik-outpost
  - metrics-server
  - reloader
  - volsync
  - metallb
  - longhorn
  - newt
