apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: infisical
spec:
  provider:
    infisical:
      hostAPI: https://eu.infisical.com
      auth:
        universalAuthCredentials:
          clientId:
            name: infisical-universal-auth
            namespace: flux-system
            key: clientId
          clientSecret:
            name: infisical-universal-auth
            namespace: flux-system
            key: clientSecret
      secretsScope:
        projectSlug: homelab
        environmentSlug: prod
