apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: longhorn-idrive
  namespace: longhorn-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: longhorn-idrive
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      data:
        AWS_ACCESS_KEY_ID: "{{ .accessKeyID }}"
        AWS_ENDPOINTS: "https://{{ .endpoint }}"
        AWS_REGION: "{{ .region }}"
        AWS_SECRET_ACCESS_KEY: "{{ .secretAccessKey }}"
  data:
    - secretKey: accessKeyID
      remoteRef:
        key: /platform/idrive-credentials/ACCESS_KEY_ID
    - secretKey: secretAccessKey
      remoteRef:
        key: /platform/idrive-credentials/ACCESS_SECRET_KEY
    - secretKey: endpoint
      remoteRef:
        key: /platform/idrive-credentials/E2_ENDPOINT
    - secretKey: region
      remoteRef:
        key: /platform/idrive-credentials/AWS_REGION
