apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: alloy-loki-client
  namespace: observability
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: alloy-loki-client
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      data:
        tls.crt: "{{ .cert }}"
        tls.key: "{{ .key }}"
        ca: "{{ .ca }}"
        tenantId: fake
  data:
    - secretKey: cert
      remoteRef:
        key: /platform/loki/CLIENT_CERT
    - secretKey: key
      remoteRef:
        key: /platform/loki/CLIENT_KEY
    - secretKey: ca
      remoteRef:
        key: /platform/loki/CA_CERT
