apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: k8s-monitoring
  namespace: flux-system
spec:
  interval: 30m
  releaseName: k8s-monitoring
  targetNamespace: observability
  chart:
    spec:
      chart: k8s-monitoring
      version: 4.4.0
      interval: 24h
      sourceRef:
        kind: HelmRepository
        name: grafana
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    cluster:
      name: homelab
    destinations:
      loki:
        type: loki
        url: https://loki.kakatkarakshay.dev/loki/api/v1/push
        secret:
          create: false
          name: alloy-loki-client
        tls:
          certKey: tls.crt
          keyKey: tls.key
          caFile: /etc/ssl/certs/ca-certificates.crt
        tenantIdKey: tenantId
    podLogsViaLoki:
      enabled: true
      collector: alloy-logs
    clusterEvents:
      enabled: true
      collector: alloy-singleton
    collectors:
      alloy-logs:
        presets: [filesystem-log-reader, daemonset]
      alloy-singleton:
        presets: [singleton]
