apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: external-snapshotter
  namespace: flux-system
spec:
  interval: 24h
  ref:
    tag: v8.6.0
    commit: d39e21b292f6b9bf2c67a53ab6613149bddb59b2
  url: https://github.com/kubernetes-csi/external-snapshotter.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-snapshotter-crds
  namespace: flux-system
spec:
  interval: 24h
  retryInterval: 1m
  path: ./client/config/crd
  prune: true
  wait: true
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: external-snapshotter
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: snapshot-controller
  namespace: flux-system
spec:
  dependsOn:
    - name: external-snapshotter-crds
  interval: 24h
  retryInterval: 1m
  path: ./deploy/kubernetes/snapshot-controller
  prune: true
  wait: true
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: external-snapshotter
