apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: kubelet-serving-cert-approver
  namespace: flux-system
spec:
  interval: 24h
  ref:
    tag: v0.11.1
    commit: 489aad3ab2fd382076a9a16d67da5752795f6271
  url: https://github.com/alex1989hu/kubelet-serving-cert-approver.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kubelet-serving-cert-approver
  namespace: flux-system
spec:
  interval: 24h
  retryInterval: 1m
  path: ./deploy/standalone
  prune: true
  wait: true
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: kubelet-serving-cert-approver
