apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: kubelet-serving-cert-approver
  namespace: flux-system
spec:
  interval: 24h
  ref:
    tag: v0.12.0
    commit: b5516301e48f8e50cb18368e457779d01796119b
  url: https://github.com/alex1989hu/kubelet-serving-cert-approver.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kubelet-serving-cert-approver
  namespace: flux-system
spec:
  interval: 24h
  retryInterval: 1m
  path: ./deploy/standalone
  prune: true
  wait: true
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: kubelet-serving-cert-approver
