apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: kubelet-serving-cert-approver
  namespace: flux-system
spec:
  interval: 24h
  ref:
    tag: v0.11.0
    commit: 48be2ff71bbdfc464763fe6dba58b43a8ec5996a
  url: https://github.com/alex1989hu/kubelet-serving-cert-approver.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kubelet-serving-cert-approver
  namespace: flux-system
spec:
  interval: 24h
  retryInterval: 1m
  path: ./deploy/standalone
  prune: true
  wait: true
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: kubelet-serving-cert-approver
