apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-outpost-token
  namespace: authentik
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: authentik-outpost-token
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: token
      remoteRef:
        key: /platform/authentik/OUTPOST_TOKEN
