apiVersion: v1
kind: Service
metadata:
  name: authentik-outpost
  namespace: authentik
  labels:
    app.kubernetes.io/name: authentik-outpost
spec:
  selector:
    app.kubernetes.io/name: authentik-outpost
  ports:
    - name: http
      port: 9000
      targetPort: http
      protocol: TCP
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: outpost-from-protected-apps
  namespace: authentik
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: home-assistant
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: longhorn-system
  to:
    - group: ""
      kind: Service
      name: authentik-outpost
