apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: bluebubbles
  namespace: bluebubbles
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
spec:
  gatewayClassName: traefik
  listeners:
    - name: https
      hostname: bluebubbles.kakatkarakshay.dev
      port: 443
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - name: bluebubbles-kakatkarakshay-dev-tls
