apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: reloader
  namespace: flux-system
spec:
  interval: 30m
  releaseName: reloader
  targetNamespace: reloader
  chart:
    spec:
      chart: reloader
      version: 2.2.16
      interval: 24h
      sourceRef:
        kind: HelmRepository
        name: stakater
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    reloader:
      autoReloadAll: true
      readOnlyRootFileSystem: true
      deployment:
        resources:
          requests:
            cpu: 10m
            memory: 64Mi
          limits:
            memory: 128Mi
