apiVersion: v1
kind: ConfigMap
metadata:
  name: blocky-config
  namespace: blocky
data:
  00-blocky.yaml: |
    upstreams:
      init:
        strategy: fast
      strategy: parallel_best
      timeout: 2s
      groups:
        default:
          - https://one.one.one.one/dns-query
          - https://dns.quad9.net/dns-query
          - tcp-tls:dns.quad9.net:853

    bootstrapDns:
      - tcp+udp:1.1.1.1
      - tcp+udp:9.9.9.9

    connectIPVersion: dual

    customDNS:
      customTTL: 1h
      filterUnmappedTypes: true
      mapping:
        blocky-homelab.kakatkarakshay.dev: 192.168.30.10
        bluebubbles.kakatkarakshay.dev: 192.168.30.10
        dns.kakatkarakshay.dev: 192.168.30.10
        "/^.+\\.dns\\.kakatkarakshay\\.dev$/": 192.168.30.10
        home-assistant.kakatkarakshay.dev: 192.168.30.10
        homelab.kakatkarakshay.dev: 192.168.30.10
        homelab-gateway.kakatkarakshay.dev: 192.168.30.10
        immich.kakatkarakshay.dev: 192.168.30.10
        longhorn-homelab.kakatkarakshay.dev: 192.168.30.10
        node-red.kakatkarakshay.dev: 192.168.30.10

    blocking:
      denylists:
        ads:
          - https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/wildcard/ultimate.txt
        malware:
          - https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/wildcard/tif.txt
      clientGroupsBlock:
        default:
          - ads
          - malware
      blockType: zeroIp
      blockTTL: 1m
      loading:
        refreshPeriod: 24h
        strategy: fast
        concurrency: 8
        downloads:
          timeout: 60s
          attempts: 5
          cooldown: 10s

    caching:
      minTime: 5m
      maxTime: 30m
      prefetching: true
      prefetchExpires: 2h
      prefetchThreshold: 5
      cacheTimeNegative: 30m

    redis:
      address: dragonfly.blocky.svc.cluster.local:6379
      required: false
      connectionAttempts: 10
      connectionCooldown: 3s

    ports:
      dns: 53
      http: 4000
      dohPath: /dns-query

    prometheus:
      enable: true

    ede:
      enable: true

    log:
      level: info
      format: json
